13) 판다스 DataFrame 실습 1
- 터미널에서 seaborn 라이브러리 설치
- seaborn은 Pandas 데이터프레임을 이용해 통계 그래프를 쉽게 그리는 Python 시각화 라이브러리이다.
- 시각화에 사용되는 실습용 샘플 데이터셋도 함께 제공한다.

In [3]:
import seaborn as sns
mpg = sns.load_dataset('mpg')
mpg.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

In [4]:
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [5]:
# 문제 1. []로 열 선택
# mpg 데이터프레임에서 mpg 열만 선택하여 출력하시오.
# mpg[['mpg']]
print(mpg[['mpg']].head())

    mpg
0  18.0
1  15.0
2  18.0
3  16.0
4  17.0

In [6]:
# 문제 2. []로 여러 열 선택
# mpg 데이터프레임에서 mpg, weight, origin 세 개의 열을 선택하여 출력하시오.
print(mpg[['mpg', 'weight', 'origin']])

      mpg  weight  origin
0    18.0    3504     usa
1    15.0    3693     usa
2    18.0    3436     usa
3    16.0    3433     usa
4    17.0    3449     usa
..    ...     ...     ...
393  27.0    2790     usa
394  44.0    2130  europe
395  32.0    2295     usa
396  28.0    2625     usa
397  31.0    2720     usa

[398 rows x 3 columns]

In [7]:
# 문제 3. iloc로 특정 행 선택
# mpg에서 10번째 행의 데이터를 출력하시오.
# 단, 숫자 위치를 이용하는 iloc을 사용하시오.
print(mpg.iloc[9])

mpg                           15.0
cylinders                        8
displacement                 390.0
horsepower                   190.0
weight                        3850
acceleration                   8.5
model_year                      70
origin                         usa
name            amc ambassador dpl
Name: 9, dtype: object

In [8]:
# 문제 4. iloc로 행 + 열 선택
# mpg에서 3번째 행의 1번째 열 값을 출력하시오.
print(mpg.iloc[2, 0])

18.0

In [9]:
# 문제 5. iloc로 행 + 열 슬라이싱
# mpg에서 1~5번째 행과 1~3번째 열을 선택하여 출력하시오.
print(mpg.iloc[0:5, 0:3])

    mpg  cylinders  displacement
0  18.0          8         307.0
1  15.0          8         350.0
2  18.0          8         318.0
3  16.0          8         304.0
4  17.0          8         302.0

In [10]:
# 문제 6. loc로 특정 행 + 열 선택
# mpg에서 인덱스가 10인 행의 mpg 값을 출력하시오.
print(mpg.loc[10, 'mpg'])

15.0

In [11]:
# 문제 7. loc로 여러 행 + 열 선택
# 인덱스가 10~15인 행에서
# - mpg
# - weight
# - origin
# 열만 선택하여 출력하시오.
print(mpg.loc[10:15, ['mpg', 'weight', 'origin']])

     mpg  weight origin
10  15.0    3563    usa
11  14.0    3609    usa
12  15.0    3761    usa
13  14.0    3086    usa
14  24.0    2372  japan
15  22.0    2833    usa

In [12]:
# 문제 8. loc 슬라이싱
# mpg에서 인덱스 10부터 15까지의 데이터를 선택하시오.
print(mpg.loc[10:15, :])

     mpg  cylinders  displacement  horsepower  weight  acceleration  \
10  15.0          8         383.0       170.0    3563          10.0
11  14.0          8         340.0       160.0    3609           8.0
12  15.0          8         400.0       150.0    3761           9.5
13  14.0          8         455.0       225.0    3086          10.0
14  24.0          4         113.0        95.0    2372          15.0
15  22.0          6         198.0        95.0    2833          15.5

    model_year origin                     name
10          70    usa      dodge challenger se
11          70    usa       plymouth 'cuda 340
12          70    usa    chevrolet monte carlo
13          70    usa  buick estate wagon (sw)
14          70  japan    toyota corona mark ii
15          70    usa          plymouth duster

In [13]:
# 문제 9. 조건으로 행 선택
# mpg에서 mpg가 30 이상인 자동차만 선택하시오.
print(mpg[mpg['mpg'] >= 30])

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
51   30.0          4          79.0        70.0    2074          19.5
52   30.0          4          88.0        76.0    2065          14.5
53   31.0          4          71.0        65.0    1773          19.0
54   35.0          4          72.0        69.0    1613          18.0
129  31.0          4          79.0        67.0    1950          19.0
..    ...        ...           ...         ...     ...           ...
390  32.0          4         144.0        96.0    2665          13.9
391  36.0          4         135.0        84.0    2370          13.0
394  44.0          4          97.0        52.0    2130          24.6
395  32.0          4         135.0        84.0    2295          11.6
397  31.0          4         119.0        82.0    2720          19.4

     model_year  origin                 name
51           71  europe          peugeot 304
52           71  europe            fiat 124b
53           71   japan  toyota corolla 1200
54           71   japan          datsun 1200
129          74   japan          datsun b210
..          ...     ...                  ...
390          82   japan     toyota celica gt
391          82     usa    dodge charger 2.2
394          82  europe            vw pickup
395          82     usa        dodge rampage
397          82     usa           chevy s-10

[92 rows x 9 columns]

In [14]:
# ​문제 10. 조건 + 열 선택
# mpg가 30 이상인 자동차의 name과 mpg만 출력하시오.
print(mpg.loc[mpg['mpg'] >= 30, ['name', 'mpg']])

                    name   mpg
51           peugeot 304  30.0
52             fiat 124b  30.0
53   toyota corolla 1200  31.0
54           datsun 1200  35.0
129          datsun b210  31.0
..                   ...   ...
390     toyota celica gt  32.0
391    dodge charger 2.2  36.0
394            vw pickup  44.0
395        dodge rampage  32.0
397           chevy s-10  31.0

[92 rows x 2 columns]

In [15]:
# 문제 11. 두 조건으로 행 선택
# mpg가 30 이상이고 weight가 2000 이하인 자동차만 출력하시오.
print(mpg.loc[(mpg['mpg'] >= 30) & (mpg['weight'] <= 2000)])

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
53   31.0          4          71.0        65.0    1773          19.0
54   35.0          4          72.0        69.0    1613          18.0
129  31.0          4          79.0        67.0    1950          19.0
131  32.0          4          71.0        65.0    1836          21.0
144  31.0          4          76.0        52.0    1649          16.5
151  31.0          4          79.0        67.0    2000          16.0
181  33.0          4          91.0        53.0    1795          17.5
198  33.0          4          91.0        53.0    1795          17.4
204  32.0          4          85.0        70.0    1990          17.0
218  36.0          4          79.0        58.0    1825          18.6
220  33.5          4          85.0        70.0    1945          16.8
239  30.0          4          97.0        67.0    1985          16.4
244  43.1          4          90.0        48.0    1985          21.5
245  36.1          4          98.0        66.0    1800          14.4
246  32.8          4          78.0        52.0    1985          19.4
248  36.1          4          91.0        60.0    1800          16.4
278  31.5          4          89.0        71.0    1990          14.9
293  31.9          4          89.0        71.0    1925          14.0
294  34.1          4          86.0        65.0    1975          15.2
295  35.7          4          98.0        80.0    1915          14.4
310  38.1          4          89.0        60.0    1968          18.8
329  44.6          4          91.0        67.0    1850          13.8
330  40.9          4          85.0         NaN    1835          17.3
343  39.1          4          79.0        58.0    1755          16.9
344  39.0          4          86.0        64.0    1875          16.4
345  35.1          4          81.0        60.0    1760          16.1
347  37.0          4          85.0        65.0    1975          19.4
349  34.1          4          91.0        68.0    1985          16.0
375  36.0          4         105.0        74.0    1980          15.3
377  31.0          4          91.0        68.0    1970          17.6
383  38.0          4          91.0        67.0    1965          15.0
384  32.0          4          91.0        67.0    1965          15.7
385  38.0          4          91.0        67.0    1995          16.2

     model_year  origin                             name
53           71   japan              toyota corolla 1200
54           71   japan                      datsun 1200
129          74   japan                      datsun b210
131          74   japan              toyota corolla 1200
144          74   japan                    toyota corona
151          74  europe                        fiat x1.9
181          75   japan                 honda civic cvcc
198          76   japan                      honda civic
204          76   japan                     datsun b-210
218          77  europe                    renault 5 gtl
220          77   japan            datsun f-10 hatchback
239          77   japan                        subaru dl
244          78  europe  volkswagen rabbit custom diesel
245          78     usa                      ford fiesta
246          78   japan                 mazda glc deluxe
248          78   japan                 honda civic cvcc
278          78  europe              volkswagen scirocco
293          79  europe                 vw rabbit custom
294          79   japan                 maxda glc deluxe
295          79     usa      dodge colt hatchback custom
310          80   japan            toyota corolla tercel
329          80   japan              honda civic 1500 gl
330          80  europe             renault lecar deluxe
343          81   japan                   toyota starlet
344          81     usa                   plymouth champ
345          81   japan                 honda civic 1300
347          81   japan                   datsun 210 mpg
349          81   japan                      mazda glc 4
375          82  europe              volkswagen rabbit l
377          82   japan                 mazda glc custom
383          82   japan                      honda civic
384          82   japan               honda civic (auto)
385          82   japan                    datsun 310 gx

1. 입력, 수정, 삭제

(간단한 CRUD방법만 실습하고, 데이터 전처리 챕터에서 좀 더 상세히 설명한다)

In [14]:
import pandas as pd

df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최수진', '정우진'],
    '학년': [1, 2, 1, 3, 2],
    '점수': [85, 92, 78, 95, 88],
    '출석': [90, 95, 80, 98, 85]
})

print(df)

    이름  학년  점수  출석
0  김철수   1  85  90
1  이영희   2  92  95
2  박민수   1  78  80
3  최수진   3  95  98
4  정우진   2  88  85

In [ ]:
# 새로운 열 추가
df['성적'] = ['B', 'A', 'C', 'A+', 'B+']
print(df)

    이름  학년  점수  출석  성적
0  김철수   1  85  90   B
1  이영희   2  92  95   A
2  박민수   1  78  80   C
3  최수진   3  95  98  A+
4  정우진   2  88  85  B+

In [16]:
# 계산해서 새로운 열 만들기

df['총점'] = df['점수'] + df['출석']
print(df)

    이름  학년  점수  출석  성적   총점
0  김철수   1  85  90   B  175
1  이영희   2  92  95   A  187
2  박민수   1  78  80   C  158
3  최수진   3  95  98  A+  193
4  정우진   2  88  85  B+  173

In [17]:
# 특정 값 수정

df.loc[0, '점수'] = 90
print(df)

    이름  학년  점수  출석  성적   총점
0  김철수   1  90  90   B  175
1  이영희   2  92  95   A  187
2  박민수   1  78  80   C  158
3  최수진   3  95  98  A+  193
4  정우진   2  88  85  B+  173

In [18]:
df.loc[df['점수'] < 80, '점수'] = 80
print(df)

    이름  학년  점수  출석  성적   총점
0  김철수   1  90  90   B  175
1  이영희   2  92  95   A  187
2  박민수   1  80  80   C  158
3  최수진   3  95  98  A+  193
4  정우진   2  88  85  B+  173

삭제 drop(열이름 or 레이블 인덱스)메서드

* drop()에 매개값으로 위치값을 사용할 수 없다
- 행삭제 : drop('행 레이블', axis=0)
- axis=0이면 첫번째 매개값을 행 레이블(인덱스)에서 찾음.
- axis=1이면 첫전째 매개값을 열 레이블(이름)에서 찾음.
- axis=0은 행축(세로방향으로 삭제 - 행들을 세로방향? 하나이상의 행들들을 삭제 가능)

In [19]:
df = df.drop(0, axis=0) # axis는 생략하면 0

In [20]:
# '총점'을 열 방향(axis=1)에서 삭제
df.drop('총점', axis=1) # axis는 생략하면 0

    이름  학년  점수  출석  성적
1  이영희   2  92  95   A
2  박민수   1  80  80   C
3  최수진   3  95  98  A+
4  정우진   2  88  85  B+

In [ ]:
print(df.shape) # (행, 열)
print(df.columns) # 가로축 레이블
print(df.index) # 세로축 레이블
print(df.dtypes) # 데이터 타입

(4, 6)
Index(['이름', '학년', '점수', '출석', '성적', '총점'], dtype='str')
RangeIndex(start=1, stop=5, step=1)
이름      str
학년    int64
점수    int64
출석    int64
성적      str
총점    int64
dtype: object

In [22]:
# 2. 통계 관련 메서드
# 1) 전체 통계량

df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최수진', '정우진'],
    '학년': [1, 2, 1, 3, 2],
    '점수': [85, 92, 78, 95, 88],
    '출석': [90, 95, 80, 98, 85]
})

print(df.count())

print(df.sum(numeric_only=True))

print(df.mean(numeric_only=True))

print(df.median(numeric_only=True))

print(df.min(numeric_only=True))

print(df.max(numeric_only=True))

print(df.std(numeric_only=True))

print(df.std(numeric_only=True))

print(df['점수'].max() - df['점수'].min())

이름    5
학년    5
점수    5
출석    5
dtype: int64
학년      9
점수    438
출석    448
dtype: int64
학년     1.8
점수    87.6
출석    89.6
dtype: float64
학년     2.0
점수    88.0
출석    90.0
dtype: float64
학년     1
점수    78
출석    80
dtype: int64
학년     3
점수    95
출석    98
dtype: int64
학년    0.836660
점수    6.580274
출석    7.300685
dtype: float64
학년    0.836660
점수    6.580274
출석    7.300685
dtype: float64
17

In [23]:
print(df.describe())

            학년         점수         출석
count  5.00000   5.000000   5.000000
mean   1.80000  87.600000  89.600000
std    0.83666   6.580274   7.300685
min    1.00000  78.000000  80.000000
25%    1.00000  85.000000  85.000000
50%    2.00000  88.000000  90.000000
75%    2.00000  92.000000  95.000000
max    3.00000  95.000000  98.000000

In [24]:
# 2) 특정 열의 통계량

print(df['점수'].mean())
print(df['점수'].median())
print(df['점수'].min())
print(df['점수'].max())
print(df['점수'].std())

87.6
88.0
78
95
6.58027355054484

In [25]:
# 수치형열의 describe() vs 범주형열의 describe()

# 3) 기타

print(df.isnull())
# True  → 결측값
# False → 결측값 아님

print(df.isnull().sum()) # 결측값 개수

print(df.duplicated()) # 중복 행 여부
# True  → 중복 행
# False → 중복 아님

print(df['학년'].unique()) # 고유값 확인 : 학년 열에 어떤 값들이 존재하는지 확인한다.
print(df['학년'].nunique()) # 고유값 개수

print(df['학년'].value_counts()) # 값별 개수

print(df['점수'].isnull()) # 특정 열의 결측값

      이름     학년     점수     출석
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
이름    0
학년    0
점수    0
출석    0
dtype: int64
0    False
1    False
2    False
3    False
4    False
dtype: bool
[1 2 3]
3
학년
1    2
2    2
3    1
Name: count, dtype: int64
0    False
1    False
2    False
3    False
4    False
Name: 점수, dtype: bool

In [26]:
# 학년의 데이터 타입을 category 타입(범주형)으로 변환한 결과를 
# 다시 df['학년']에 저장하여 df의 학년 데이터 타입을 변경
df['학년'] = df['학년'].astype('category')

print(df['학년'].dtype)

category