DataFrame
- 표와 같은 스프레드시트 형식의 자료구조
- NumPy에 비유 하면 2차원 array   
- 색인의 모양이 같은 Series 객체를 담고 있는 파이썬 딕셔너리라고 생각해도 무방
- 서로 다른 종류의값(숫자, 문자열, 불리언등)을 담을 수 있는 여러칼럼을 가질 수 있다
- (2차원 array는 동일한 데이터타입을 가져야 하지만, DataFrame은 열마다 다른 타입)

1. DataFrame <br>
- DataFrame클래스 생성자
- 파라미터: pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)

DataFrame생성자의 data 매개값으로 자주 사용하는 데이터 타입

- 2차원ndarray
- 배열, 리스트, 사전
- Series 사전
- 다른DataFrame

In [1]:
import pandas as pd

df = pd.DataFrame(
    [[90, 80],
     [70, 60]],
    columns=['국어', '영어']
)

print(df)

   국어  영어
0  90  80
1  70  60

In [3]:
# {레이블: [], 레이블: []}
df1 = pd.DataFrame({
    "이름":["민수", "지영"],
    "점수":[90, 80]
})

# print() 터미널 출력
# display() 주피터 노트북 출력
df1

   이름  점수
0  민수  90
1  지영  80

In [6]:
# index값 행레이블(레이블 인덱스), columns값 열레이블(레이블 컬럼)
# 생략하면 위치값으로 기본값 설정된다.

df2 = pd.DataFrame([
    ['민수', 90], # 1명
    ['지영', 80] # 2명
], index=['첫번째', '두번째'], columns=['이름', '점수'])

df2

     이름  점수
첫번째  민수  90
두번째  지영  80

In [1]:
import pandas as pd

# 이름, 나이, 성별 데이터로 DataFrame 생성
df = pd.DataFrame({
    '이름': ['철수', '영희', '민수', '지영', '준호'],
    '나이': [20, 21, 20, 22, 21],
    '성별': ['남', '여', '남', '여', '남']
})

print(df)

   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남

In [ ]:
# 1) info() 메서드
# 행 개수, 열 개수, 열 이름, 결측값이 아닌 데이터 개수, 데이터 타입 확인

print("===== info =====")
# DataFrame의 전체 정보를 출력
df.info()

===== info =====
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      str
 1   나이      5 non-null      int64
 2   성별      5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [ ]:
# 2) shape, size, ndim
# 행과 열의 크기

print("shape:", df.shape) # 출력 (행 개수, 열 개수)

print("행 개수:", df.shape[0])
print("열 개수:", df.shape[1])

print(df.shape, df.size, df.ndim)

shape: (5, 3)
행 개수: 5
열 개수: 3
(5, 3) 15 2

In [4]:
# 3) dtypes
# 각 열의 데이터 타입

print("===== dtypes =====")
print(df.dtypes)

# 특정 열의 데이터 타입 확인
print(df['나이'].dtype)
print(df['이름'].dtype)

===== dtypes =====
이름      str
나이    int64
성별      str
dtype: object
int64
str

In [5]:
# 4) columns
# 열 이름 확인

print("===== columns =====")
print(df.columns)

# 이름만 확인
print(df.columns.tolist())

# in 연산자를 사용하여 특정 열의 존재 유무 확인
print('나이' in df.columns)
print('주소' in df.columns)

===== columns =====
Index(['이름', '나이', '성별'], dtype='str')
['이름', '나이', '성별']
True
False

In [6]:
# 5) index
# 행 레이블 인덱스 확인(위치값 인덱스 아님)
print("===== index =====")
print(df.index)

===== index =====
RangeIndex(start=0, stop=5, step=1)

In [7]:
# 6) head, tail
print("===== head =====")
print(df.head()) # 기본값으로 5행
print(df.head(3))

print("===== tail =====")
print(df.tail())
print(df.tail(3))

===== head =====
   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남
   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
===== tail =====
   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남
   이름  나이 성별
2  민수  20  남
3  지영  22  여
4  준호  21  남

In [8]:
# 7) unique, nunique
# 고유값 확인, 고유값 개수
print(df['성별'].unique())
print(df['나이'].unique())

# 고유값 개수
print(df['성별'].nunique())

<StringArray>
['남', '여']
Length: 2, dtype: str
[20 21 22]
2

12) 판다스 DataFrame타입 데이터 추출하기

- 행과 열을 동시에 선택 <br>
loc[]: 인덱스 → 레이블 기준으로 행/열 선택 <br>
iloc[]: 인덱스 → 숫자 위치 기준으로 행/열 선택 <br>

- 행과 열 중 하나만 선택 <br>
df[]: <br>
연산자 → 열이름 → 열을 선택하면 → 행은 전체 → 특정 열의 모든 행 <br>
조건식 → 행 선택 : 행을 선택하면 → 열은 전체 → 특정 행의 모든 열 <br>
슬라이싱 → 행 선택 : 행을 선택하면 → 열은 전체 → 특정 행의 모든 열

In [2]:
# 실습용 데이터 프레임
import pandas as pd

df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최수진', '정우진'],
    '학년': [1, 2, 1, 3, 2],
    '점수': [85, 92, 78, 95, 88]
}, index=['A', 'B', 'C', 'D', 'E'])

print(df)

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

- 행 레이블 인덱스 → A, B, C, D, E

- 행 위치 → 0, 1, 2, 3, 4



- 열 이름 → 이름, 학년, 점수

- 열 위치 → 0, 1, 2

1) loc인덱스 : 행 인덱스, 열이름 사용

In [3]:
# loc[행 인덱스, 열 이름]

print(df.loc['B', '점수']) # 92

# 여러행, 여러 열 선택 시 []안에 리스트 사용
print(df.loc[['B', 'D'], ['이름', '점수']])

92
    이름  점수
B  이영희  92
D  최수진  95

In [11]:
# loc[행 인덱스 슬라이싱, 열 이름 슬라이싱]
df.loc['B':'D', '이름':'학년']

    이름  학년
B  이영희   2
C  박민수   1
D  최수진   3

2) iloc인덱스 : 행 위치, 열 위치 사용

In [12]:
# iloc[행 위치, 열 위치]

print(df.iloc[1, 2]) # 92

# 여러행, 여려열 선택
print(df.iloc[[1, 3], [0, 2]])

92
    이름  점수
B  이영희  92
D  최수진  95

In [13]:
# iloc[행 위치 슬라이싱, 열 위치 슬라이싱]
df.iloc[1:4, 0:2]

    이름  학년
B  이영희   2
C  박민수   1
D  최수진   3

2. [] 인덱싱 연산자
- [값] -> 열선택
- [식] -> 행선택

In [ ]:
# 1) 열 선택
# - df[숫자]
# - "열 이름이 0인 열"

# #0번째 열 아님. 0번째 열은 iloc[]인덱스를 사용하여야 한다 
# df[0] # error

# - df['이름']

# 열 이름 위치
# 두개이상의 열은 []안에 리스트를 사용하여 []안에 하나의 값형태로 입력
# df[['이름', '점수']]
# df["이름", "점수"] error! []연산자 안에는 하나의 표현식만이 올 수 있다
# - []연산자안에 매개값으로 리스트 타입이 입력되면 반환되는 타입은 하나 이상의 열을 반환하므로 DataFrame타입을 반환한다. []연산자안에 스칼라 열이 입력되면 반환타입은 Series타입을 반환.

In [ ]:
df['점수'] # Series

A    85
B    92
C    78
D    95
E    88
Name: 점수, dtype: int64

In [10]:
df[['이름', '점수']] # DataFrame

    이름  점수
A  김철수  85
B  이영희  92
C  박민수  78
D  최수진  95
E  정우진  88

In [12]:
# 하나의 열이지만 리스트형태로 입력되면 반환타입은 1열짜리 DataFram타입이 반환된다.
df[['점수']] # DataFrame

   점수
A  85
B  92
C  78
D  95
E  88

2) 행 선택

In [13]:
# 1) df[슬라이싱] : []연산자안에 슬라이싱 표현식
df[1:4] # 행을 위치 기준으로 위치 1부터 3까지 선택

    이름  학년  점수
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95

In [14]:
# 2) df[열조건] : []연산자안에 열조건 표현식
df[df['점수'] >= 90] # 조건에 맞는 행 선택

    이름  학년  점수
B  이영희   2  92
D  최수진   3  95

In [16]:
# 위랑 같음
temp = df['점수']
df[temp >= 90]

    이름  학년  점수
B  이영희   2  92
D  최수진   3  95

In [17]:
# error
# [5, 10, 15, 20] > 10 

# error가 발생하지 않게 실행하려면 컴프리핸션을 사용 
[x>10 for x in [5, 10, 15, 20]]

[False, False, True, True]

In [19]:
pd.Series([5, 10, 15, 20]) > 10
# 에러 아님 다음값을 반환(Series 내부적으로 컴프리핸션을 사용)

0    False
1    False
2     True
3     True
dtype: bool

- Python 리스트는 > 연산자를 리스트 전체에 적용하면 원소별 비교를 하지 않는다. 따라서 리스트 컴프리헨션이나 반복문을 사용해야 한다.
- pandas Series는 내부적으로 NumPy의 배열 연산 등을 활용하여 > 같은 연산자를 원소별(element-wise)로 적용할 수 있다.​

13) 판다스 DataFrame 실습 1

In [20]:
import seaborn as sns
mpg = sns.load_dataset('mpg')
mpg.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

In [21]:
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

1. 입력, 수정, 삭제

(간단한 CRUD방법만 실습하고, 데이터 전처리 챕터에서 좀 더 상세히 설명한다)

In [14]:
import pandas as pd

df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최수진', '정우진'],
    '학년': [1, 2, 1, 3, 2],
    '점수': [85, 92, 78, 95, 88],
    '출석': [90, 95, 80, 98, 85]
})

print(df)

    이름  학년  점수  출석
0  김철수   1  85  90
1  이영희   2  92  95
2  박민수   1  78  80
3  최수진   3  95  98
4  정우진   2  88  85

In [ ]:
# 새로운 열 추가
df['성적'] = ['B', 'A', 'C', 'A+', 'B+']
print(df)

    이름  학년  점수  출석  성적
0  김철수   1  85  90   B
1  이영희   2  92  95   A
2  박민수   1  78  80   C
3  최수진   3  95  98  A+
4  정우진   2  88  85  B+

In [16]:
# 계산해서 새로운 열 만들기

df['총점'] = df['점수'] + df['출석']
print(df)

    이름  학년  점수  출석  성적   총점
0  김철수   1  85  90   B  175
1  이영희   2  92  95   A  187
2  박민수   1  78  80   C  158
3  최수진   3  95  98  A+  193
4  정우진   2  88  85  B+  173

In [17]:
# 특정 값 수정

df.loc[0, '점수'] = 90
print(df)

    이름  학년  점수  출석  성적   총점
0  김철수   1  90  90   B  175
1  이영희   2  92  95   A  187
2  박민수   1  78  80   C  158
3  최수진   3  95  98  A+  193
4  정우진   2  88  85  B+  173

In [18]:
df.loc[df['점수'] < 80, '점수'] = 80
print(df)

    이름  학년  점수  출석  성적   총점
0  김철수   1  90  90   B  175
1  이영희   2  92  95   A  187
2  박민수   1  80  80   C  158
3  최수진   3  95  98  A+  193
4  정우진   2  88  85  B+  173

삭제 drop(열이름 or 레이블 인덱스)메서드

* drop()에 매개값으로 위치값을 사용할 수 없다
- 행삭제 : drop('행 레이블', axis=0)
- axis=0이면 첫번째 매개값을 행 레이블(인덱스)에서 찾음.
- axis=1이면 첫전째 매개값을 열 레이블(이름)에서 찾음.
- axis=0은 행축(세로방향으로 삭제 - 행들을 세로방향? 하나이상의 행들들을 삭제 가능)

In [19]:
df = df.drop(0, axis=0) # axis는 생략하면 0

In [20]:
# '총점'을 열 방향(axis=1)에서 삭제
df.drop('총점', axis=1) # axis는 생략하면 0

    이름  학년  점수  출석  성적
1  이영희   2  92  95   A
2  박민수   1  80  80   C
3  최수진   3  95  98  A+
4  정우진   2  88  85  B+

In [ ]:
print(df.shape) # (행, 열)
print(df.columns) # 가로축 레이블
print(df.index) # 세로축 레이블
print(df.dtypes) # 데이터 타입

(4, 6)
Index(['이름', '학년', '점수', '출석', '성적', '총점'], dtype='str')
RangeIndex(start=1, stop=5, step=1)
이름      str
학년    int64
점수    int64
출석    int64
성적      str
총점    int64
dtype: object

In [22]:
# 2. 통계 관련 메서드
# 1) 전체 통계량

df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최수진', '정우진'],
    '학년': [1, 2, 1, 3, 2],
    '점수': [85, 92, 78, 95, 88],
    '출석': [90, 95, 80, 98, 85]
})

print(df.count())

print(df.sum(numeric_only=True))

print(df.mean(numeric_only=True))

print(df.median(numeric_only=True))

print(df.min(numeric_only=True))

print(df.max(numeric_only=True))

print(df.std(numeric_only=True))

print(df.std(numeric_only=True))

print(df['점수'].max() - df['점수'].min())

이름    5
학년    5
점수    5
출석    5
dtype: int64
학년      9
점수    438
출석    448
dtype: int64
학년     1.8
점수    87.6
출석    89.6
dtype: float64
학년     2.0
점수    88.0
출석    90.0
dtype: float64
학년     1
점수    78
출석    80
dtype: int64
학년     3
점수    95
출석    98
dtype: int64
학년    0.836660
점수    6.580274
출석    7.300685
dtype: float64
학년    0.836660
점수    6.580274
출석    7.300685
dtype: float64
17

In [23]:
print(df.describe())

            학년         점수         출석
count  5.00000   5.000000   5.000000
mean   1.80000  87.600000  89.600000
std    0.83666   6.580274   7.300685
min    1.00000  78.000000  80.000000
25%    1.00000  85.000000  85.000000
50%    2.00000  88.000000  90.000000
75%    2.00000  92.000000  95.000000
max    3.00000  95.000000  98.000000

In [24]:
# 2) 특정 열의 통계량

print(df['점수'].mean())
print(df['점수'].median())
print(df['점수'].min())
print(df['점수'].max())
print(df['점수'].std())

87.6
88.0
78
95
6.58027355054484

In [25]:
# 수치형열의 describe() vs 범주형열의 describe()

# 3) 기타

print(df.isnull())
# True  → 결측값
# False → 결측값 아님

print(df.isnull().sum()) # 결측값 개수

print(df.duplicated()) # 중복 행 여부
# True  → 중복 행
# False → 중복 아님

print(df['학년'].unique()) # 고유값 확인 : 학년 열에 어떤 값들이 존재하는지 확인한다.
print(df['학년'].nunique()) # 고유값 개수

print(df['학년'].value_counts()) # 값별 개수

print(df['점수'].isnull()) # 특정 열의 결측값

      이름     학년     점수     출석
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
이름    0
학년    0
점수    0
출석    0
dtype: int64
0    False
1    False
2    False
3    False
4    False
dtype: bool
[1 2 3]
3
학년
1    2
2    2
3    1
Name: count, dtype: int64
0    False
1    False
2    False
3    False
4    False
Name: 점수, dtype: bool

In [26]:
# 학년의 데이터 타입을 category 타입(범주형)으로 변환한 결과를 
# 다시 df['학년']에 저장하여 df의 학년 데이터 타입을 변경
df['학년'] = df['학년'].astype('category')

print(df['학년'].dtype)

category