28) DataFrame 다루기 - 데이터셋 결합하기 concat(), merge() 함수

1. concat() 함수
- 전처리 - 데이터 결합하기
- concat() 함수 : 같은 구조의 데이터를 합치는 것
- axis=0 → 행을 아래로 붙인다
- axis=1 → 열을 옆으로 붙인다
- SQL의 JOIN과는 다르다.
- concat은 단순히 축을 기준으로 이어 붙이는 것이고, 
- 공통 키를 기준으로(SQL의 JOIN 유사) 데이터를 결합하려면 merge()나 join()을 사용한다.

In [ ]:
# import pandas as pd

# pd.concat( 
#     objs, # 연결할 데이터프레임들의 리스트
#     axis=0, # 연결 축 (0: 행 방향, 1: 열 방향)
#     join="outer", # 결합 방식 ("outer", "inner")
#     ignore_index=False, # 인덱스를 무시하고 새로 생성할지 여부
#     keys=None # 결과에 키 추가할지 여부
# )

0    80
1    90
2    75
Name: 점수, dtype: int64

pandas.Series

   점수
0  80
1  90
2  75

pandas.DataFrame

join은 “공통 부분만 붙일 것인가, 전체를 유지할 것인가”를 결정하는 옵션이다. SQL문의 JOIN같은 것이 아니다.

In [1]:
import pandas as pd

df1 = pd.DataFrame({
    "이름": ["홍길동", "김철수"],
    "점수": [80, 90]
})

df2 = pd.DataFrame({
    "이름": ["이영희", "박민수"],
    "점수": [85, 95]
})

display(df1)
display(df2)

    이름  점수
0  홍길동  80
1  김철수  90

    이름  점수
0  이영희  85
1  박민수  95

ignore_index=False : 기본값

In [2]:
# axis=0 위아래 결합(기본값) -> 행추가
df = pd.concat([df1, df2], ignore_index=False, axis=0) # ignore_index 기본값 False
display(df)

    이름  점수
0  홍길동  80
1  김철수  90
0  이영희  85
1  박민수  95

ignore_index=True

In [3]:
df = pd.concat([df1, df2], ignore_index=True, axis=0)
display(df)

    이름  점수
0  홍길동  80
1  김철수  90
2  이영희  85
3  박민수  95

axis=1 : 생략하면 기본값 0

In [4]:
# axis=0 좌우 결합 -> 열추가
df = pd.concat([df1, df2], axis=1) # axis=0 행축, axix=1 열축 기본값 0
display(df)

    이름  점수   이름  점수
0  홍길동  80  이영희  85
1  김철수  90  박민수  95

- join="outer" vs join="inner"
- join은 “공통 부분만 붙일 것인가, 전체를 유지할 것인가”를 결정

In [5]:
df1 = pd.DataFrame({
    "이름": ["김민수", "이서연"],
    "점수": [80, 90]
})

df2 = pd.DataFrame({
    "이름": ["박지훈", "최유진"],
    "등급": ["A", "B"]
})
display(df1)
display(df2)

    이름  점수
0  김민수  80
1  이서연  90

    이름 등급
0  박지훈  A
1  최유진  B

두 데이터 프레임의 공통된 열은 "이름"열만 존재한다.

In [6]:
df = pd.concat([df1, df2], join="outer", ignore_index=True) # join생략하면 기본값이 outer
display(df)

    이름    점수   등급
0  김민수  80.0  NaN
1  이서연  90.0  NaN
2  박지훈   NaN    A
3  최유진   NaN    B

In [ ]:
df = pd.concat([df1, df2], join="inner", ignore_index=True) # inner join -> 공통 컬럼만 남김
display(df)

    이름
0  김민수
1  이서연
2  박지훈
3  최유진

axis=1

In [8]:
import pandas as pd

df = pd.DataFrame({
    "이름": ["홍길동", "김철수", "이영희", "박민수"],
    "점수": [90, 80, 95, 70]
})

grade = pd.DataFrame({
    "등급": ["A", "B", "A", "C"]
})

result = pd.concat([df, grade], axis=1)

display(result)

    이름  점수 등급
0  홍길동  90  A
1  김철수  80  B
2  이영희  95  A
3  박민수  70  C

In [9]:
# 열의 개수가 다르면 -> join="outer"이면(기본값)  NaN으로 채워진다
df = pd.DataFrame({
    "이름": ["홍길동", "김철수", "이영희", "박민수"],
    "점수": [90, 80, 95, 70]
})

grade2 = pd.DataFrame({
    "등급": ["A", "B", "A"]
})

result = pd.concat([df, grade2], axis=1)

display(result)

    이름  점수   등급
0  홍길동  90    A
1  김철수  80    B
2  이영희  95    A
3  박민수  70  NaN

In [10]:
pd.concat([df, grade2], axis=1, join="inner")

    이름  점수 등급
0  홍길동  90  A
1  김철수  80  B
2  이영희  95  A

2. merge() 함수

- merge()는 두 DataFrame의 공통된 열(키)을 기준으로 데이터를 결합할 때 사용하는 함수
- SQL의 JOIN문의 경험이 있다면 merge()는 이해하기 쉽다.(JOIN 개념 자체는 동일하다)

In [11]:
import pandas as pd

df_customer = pd.DataFrame({
    "고객ID": [101, 102, 103, 104],
    "이름": ["홍길동", "김철수", "이영희", "박민수"]
})

df_score = pd.DataFrame({
    "고객ID": [101, 102, 103, 105],
    "점수": [90, 80, 95, 70]
})


display(df_customer)
display(df_score)

result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="inner" # inner(기본값), left, right, outer
)

display(result)

   고객ID   이름
0   101  홍길동
1   102  김철수
2   103  이영희
3   104  박민수

   고객ID  점수
0   101  90
1   102  80
2   103  95
3   105  70

   고객ID   이름  점수
0   101  홍길동  90
1   102  김철수  80
2   103  이영희  95

In [12]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="left"
)

display(result)

   고객ID   이름    점수
0   101  홍길동  90.0
1   102  김철수  80.0
2   103  이영희  95.0
3   104  박민수   NaN

In [13]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="right"
)

display(result)

   고객ID   이름  점수
0   101  홍길동  90
1   102  김철수  80
2   103  이영희  95
3   105  NaN  70

In [14]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="outer"
)

display(result)

   고객ID   이름    점수
0   101  홍길동  90.0
1   102  김철수  80.0
2   103  이영희  95.0
3   104  박민수   NaN
4   105  NaN  70.0

- 판다스 라이브러리에는 merge() 함수와 유사한 DataFrame.merge(), DataFrame.join() 같은 메서드들도 있다. 
- 비슷한 기능을 가진 merge 메서드와 join 메서드가 존재하는 이유는 사용 상황과 코드 표현 방식이 조금 다르기 때문이다. 우선은 merge()함수으로도 충분하다.

29) DataFrame 다루기 - 결측치(누락값) 처리 1

- 결측치(누락값) 메서드
1. isna(): 누락값 위치 확인
2. isna().sum(): 열별 누락값 개수
3. dropna(): 누락값이 있는 행 삭제
4. fillna(): 누락값을 다른 값으로 대체
5. mean(): 기본적으로 누락값 대체
6. sum(): 기본적으로 누락값 제외
7. count(): 누락값 제외한 데이터 개수

※ 삭제 및 대체 판단 <br>
- 결측치를 억지로 채워 넣으면 오히려 분석 모델이 추측에 의존하게 되어 결과가 심각하게 왜곡될 수 있으니 주의
- 삭제 권장 (50% 이상): 결측치가 해당 열의 50%를 넘는다면, 어떤 값으로 채워도 신뢰성이 부족해집니다. 
- 이럴 땐 해당 열 전체를 삭제하는 것이 합리적입니다.
- 대체 권장 (20~30%): 결측치가 20~30% 수준이라면 평균, 중앙값, 혹은 회귀 분석을 통한 대체법을 사용하여 데이터를 살리는 것이 좋습니다.
- 행 삭제: 결측치 수가 극소수라면 해당 행만 삭제해도 분석 결과에 큰 무리가 없습니다.

In [2]:
# 누락값 확인 isna() 또는 isnull()을 사용한다.
# None은 python에서 값이 없는 객체
# NaN은 numpy, pandas의 숫자데이터의 결측값(None을 입력해도 NaN으로 처리됨)
import pandas as pd

data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, 75, None],
    "출석": [True, True, None, True, False]
}

df = pd.DataFrame(data)

print(df) # 데이터프레임은 객체타입은 None, 숫자타입은 NaN으로 처리

print(df.isna())
print(df.isnull())

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False
      이름     점수     출석
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False
      이름     점수     출석
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

※ 불값을 sum연산을 하면 True -> 1, False -> 0 으로 계산된다 <br>
-> sum()메서드를 이용하여 결측치 개수 확인하는 방법 -> 결측치가 3개 있음을 확인

In [3]:
# 하나의 열을 분리 후 시리즈 메서드 isna()를 사용해도 된다.
print(df["점수"].isna()) # 점수열의 시리즈메서드 isna()

0    False
1     True
2    False
3    False
4     True
Name: 점수, dtype: bool

조건식 사용

In [4]:
cond = df["점수"].isna() # [False, True, False, False, True] 시리즈 반환
print(df[cond]) # df[[False, True, False, False, True]] => True인 인덱스1, 4행 출력

# 한줄의 코드로 만들면
print(df[df["점수"].isna()]) # df[조건] -> 행반환

# cond가 True 이름만 출력 => loc[] 인덱스 사용
print(df.loc[cond, "이름"]) # df[조건] -> 행반환
print(df.loc[df["점수"].isna(), "이름"]) # df[조건] -> 행반환

    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False
    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False
1    이서연
4    정현우
Name: 이름, dtype: str
1    이서연
4    정현우
Name: 이름, dtype: str

In [5]:
# 누락값 개수 확인
df.isna().sum()
# 이름    0 → 누락값 0개
# 점수    2 → 누락값 2개
# 출석    1 → 누락값 1개

이름    0
점수    2
출석    1
dtype: int64

In [6]:
print(df.isna().any()) # 데이터프레임 열에 누락값이 하나라도 있으면 True
# 이름    False
# 점수     True
# 출석     True

print(df.isna().all()) # 데이터프레임 열이 모두 누락값이면 True
# 이름    False
# 점수    False
# 출석    False

이름    False
점수     True
출석     True
dtype: bool
이름    False
점수    False
출석    False
dtype: bool

In [7]:
# 누락값 처리
# 누락값 처리는 크게 삭제와 대체 → 삭제보다는 대체

# dropna() 누락값이 있는 행 삭제한 데이터프레임을 반환
df2 = df.dropna()
print(df2)

# 원본의 행은 삭제 안됨
print(df)

    이름    점수    출석
0  김민준  85.0  True
3  최유진  75.0  True
    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

In [8]:
# 특정열의 누락값이 있는 행 삭제한 데이터프레임 반환
df2 = df.dropna(subset=["점수", "출석"])
print(df2)

df2 = df.dropna(subset=["점수"])
print(df2)

# subset=df.columns 기본값

    이름    점수    출석
0  김민준  85.0  True
3  최유진  75.0  True
    이름    점수    출석
0  김민준  85.0  True
2  박지훈  90.0  None
3  최유진  75.0  True

In [9]:
# 선택열의 누락값을 특정 값으로 대체 후 데이터셋(시리즈, 데이터프레임)반환 → fillna()
print(df["점수"].fillna(0)) # 열.fillna() 시리즈메서드 fillna() → 시리즈 반환
print(df[["점수","출석"]].fillna(0)) # 데이터프레임 메서드 fillna() → 데이터프레임 반환

# 원본에 대입
df["점수"] = df["점수"].fillna(0)
df

0    85.0
1     0.0
2    90.0
3    75.0
4     0.0
Name: 점수, dtype: float64
     점수     출석
0  85.0   True
1   0.0   True
2  90.0      0
3  75.0   True
4   0.0  False

    이름    점수     출석
0  김민준  85.0   True
1  이서연   0.0   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   0.0  False

In [10]:
# 평균값으로 누락값 대체
data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, 75, None]
}

df = pd.DataFrame(data)
df

    이름    점수
0  김민준  85.0
1  이서연   NaN
2  박지훈  90.0
3  최유진  75.0
4  정현우   NaN

In [11]:
mean_score = df["점수"].mean()
df["점수"] = df["점수"].fillna(mean_score)
print(df)

    이름         점수
0  김민준  85.000000
1  이서연  83.333333
2  박지훈  90.000000
3  최유진  75.000000
4  정현우  83.333333

In [12]:
# 중앙값으로 대체

import pandas as pd

data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, 75, None]
}

df = pd.DataFrame(data)

median_score = df["점수"].median()

df["점수"] = df["점수"].fillna(median_score)

print(df)

    이름    점수
0  김민준  85.0
1  이서연  85.0
2  박지훈  90.0
3  최유진  75.0
4  정현우  85.0

In [13]:
# 범주(Category)의 경우 최빈값 대체

import pandas as pd

data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "성별": ["M", "F", None, "F", None] 
}

df = pd.DataFrame(data)

# mode()의 반환타입은 시리즈 타입이다. 결과값을 값을 가져오기 위해 위치값 [0]이 필요
mode_gender = df["성별"].mode()[0]

df["성별"] = df["성별"].fillna(mode_gender)

print(df)

    이름 성별
0  김민준  M
1  이서연  F
2  박지훈  F
3  최유진  F
4  정현우  F

In [14]:
# 통계(집계) 연산시 누락값이 포함되어 있는 경우
# 판다스의 주요 통계 함수는 기본적으로 누락값을 제외하고 계산한다.

data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [80, None, 90, 70, None]
}

df = pd.DataFrame(data)


print("평균:", df["점수"].mean())
print("합계:", df["점수"].sum())
print("최댓값:", df["점수"].max())
print("최솟값:", df["점수"].min())

print("개수:",df["점수"].count())

평균: 80.0
합계: 240.0
최댓값: 90.0
최솟값: 70.0
개수: 3

30) DataFrame 다루기 - 연습문제

In [ ]:
# 1. concat()을 사용하여 df1과 df2를 행 방향으로 결합하시오.
# 결과가 다음과 같은 형태가 되도록 하시오.(기존 인덱스는 무시하고 새로운 인덱스 생성)
import pandas as pd

df1 = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈"],
    "점수": [85, 90, 75]
})

df2 = pd.DataFrame({
    "이름": ["최유진", "정현우", "강수빈"],
    "점수": [95, 80, 88]
})

result = pd.concat([df1, df2], ignore_index=True, axis=0)
print(result)

    이름  점수
0  김민준  85
1  이서연  90
2  박지훈  75
3  최유진  95
4  정현우  80
5  강수빈  88

In [ ]:
# 2. 두 DataFrame을 열 방향으로 결합하시오.
result = pd.concat([df1, df2], axis=1)
print(result)

    이름  점수   이름  점수
0  김민준  85  최유진  95
1  이서연  90  정현우  80
2  박지훈  75  강수빈  88

In [ ]:
# 데이터 준비
students = pd.DataFrame({
    "학생ID": [101, 102, 103, 104],
    "이름": ["김민준", "이서연", "박지훈", "최유진"]
})

scores = pd.DataFrame({
    "학생ID": [101, 102, 103, 104],
    "점수": [85, 90, 75, 95]
})

In [22]:
# 3. 학생ID를 기준으로 두 DataFrame을 결합하시오.
result = pd.merge(
    students,
    scores,
    on="학생ID",
    how="inner" # inner(기본값), left, right, outer
)
print(result)

   학생ID   이름  점수
0   101  김민준  85
1   102  이서연  90
2   103  박지훈  75
3   104  최유진  95

In [ ]:
# 데이터 준비
customer = pd.DataFrame({
    "고객ID": [1, 2, 3],
    "이름": ["김민준", "이서연", "박지훈"]
})

order = pd.DataFrame({
    "고객ID": [1, 2, 3],
    "상품": ["노트북", "마우스", "키보드"],
    "금액": [1200000, 30000, 80000]
})

In [24]:
# 4. 고객ID를 기준으로 두 DataFrame을 merge()하시오.
# 결과에 다음 컬럼이 포함되도록 하시오.
# 고객ID, 이름, 상품, 금액

result = pd.merge(
    customer,
    order,
    on="고객ID",
    how="inner" # inner(기본값), left, right, outer
)
print(result)

   고객ID   이름   상품       금액
0     1  김민준  노트북  1200000
1     2  이서연  마우스    30000
2     3  박지훈  키보드    80000

In [27]:
# 데이터 준비
employee = pd.DataFrame({
    "사번": [101, 102, 103, 104],
    "이름": ["김민준", "이서연", "박지훈", "최유진"],
    "부서ID": [10, 20, 10, 30]
})

department = pd.DataFrame({
    "부서ID": [10, 20, 30],
    "부서명": ["개발팀", "인사팀", "영업팀"]
})

In [28]:
# 5. 부서ID를 기준으로 두 DataFrame을 결합하여 다음과 같은 결과를 만드시오.

result = pd.merge(
    employee,
    department,
    on="부서ID",
    how="inner" # inner(기본값), left, right, outer
)
print(result)

    사번   이름  부서ID  부서명
0  101  김민준    10  개발팀
1  102  이서연    20  인사팀
2  103  박지훈    10  개발팀
3  104  최유진    30  영업팀

6. 
① 결측치의 위치를 확인하시오. <br>
② 각 컬럼의 결측치 개수를 확인하시오. <br>
③ 전체 결측치의 개수를 구하시오.

In [30]:
# 데이터 준비
df = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, None, 80],
    "출석": [True, True, None, True, None]
})

print(df)

    이름    점수    출석
0  김민준  85.0  True
1  이서연   NaN  True
2  박지훈  90.0  None
3  최유진   NaN  True
4  정현우  80.0  None

In [ ]:
# 결측치 위치 확인
result = df.isna()
print(result)

      이름     점수     출석
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False
4  False  False   True

In [33]:
# 결측치 개수 확인
result = df.isna().sum()
print(result)

이름    0
점수    2
출석    2
dtype: int64

In [34]:
# 전체 결측치 개수 확인
result = df.isna().sum().sum()
print(result)

4

In [35]:
# 데이터 준비
df = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈", "최유진"],
    "점수": [85, None, 90, 75]
})

In [36]:
# 7. 점수에 결측치가 있는 행을 삭제하시오.

df_cleaned = df.dropna(subset=["점수"])
print(df_cleaned)

    이름    점수
0  김민준  85.0
2  박지훈  90.0
3  최유진  75.0

8. 
① 점수의 평균을 구하시오. <br>
② 결측치를 평균으로 대체하시오. <br>
③ 처리된 DataFrame을 출력하시오. <br>

In [ ]:
# 데이터 준비
df = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [80, None, 90, 70, None]
})

In [38]:
# 점수의 평균
mean_score = df["점수"].mean()
print("점수의 평균:", mean_score)

점수의 평균: 80.0

In [39]:
# 결측치를 평균 값으로 대체
df["점수"] = df["점수"].fillna(mean_score)
print(df)

    이름    점수
0  김민준  80.0
1  이서연  80.0
2  박지훈  90.0
3  최유진  70.0
4  정현우  80.0

In [40]:
# 처리된 df 출력
print(df)

    이름    점수
0  김민준  80.0
1  이서연  80.0
2  박지훈  90.0
3  최유진  70.0
4  정현우  80.0

9. 
① 지역의 최빈값을 구하시오. <br>
② 결측치를 최빈값으로 대체하시오. <br>
③ 처리된 DataFrame을 출력하시오.

In [41]:
# 데이터 준비
df = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "지역": ["서울", "부산", None, "서울", None]
})

In [42]:
# 지역의 최빈값
mode_region = df["지역"].mode()[0]
print("지역의 최빈값:", mode_region)

지역의 최빈값: 서울

In [43]:
# 결측치를 최빈값으로 대체
df["지역"] = df["지역"].fillna(mode_region)
print(df)

    이름  지역
0  김민준  서울
1  이서연  부산
2  박지훈  서울
3  최유진  서울
4  정현우  서울

In [44]:
# 처리된 df 출력
print(df)

    이름  지역
0  김민준  서울
1  이서연  부산
2  박지훈  서울
3  최유진  서울
4  정현우  서울

10. 학생 정보와 시험 점수가 각각 다른 DataFrame에 저장되어 있다.

① 학생ID를 기준으로 두 DataFrame을 merge()하시오. <br>
② 모든 학생이 결과에 포함되도록 하시오. <br>
③ 점수의 결측치 개수를 확인하시오. <br>
④ 점수의 평균값으로 결측치를 대체하시오. <br>
⑤ 최종 DataFrame을 출력하시오. <br>

In [45]:
# 데이터 준비
students = pd.DataFrame({
    "학생ID": [101, 102, 103, 104, 105],
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"]
})

scores = pd.DataFrame({
    "학생ID": [101, 102, 104, 105],
    "점수": [85, None, 90, 75]
})

In [46]:
# 학생id를 기준으로 두 DataFrame을 merge()하시오.
result = pd.merge(
    students,
    scores,
    on="학생ID",
    how="left" # left join
)
print(result)

   학생ID   이름    점수
0   101  김민준  85.0
1   102  이서연   NaN
2   103  박지훈   NaN
3   104  최유진  90.0
4   105  정현우  75.0

In [47]:
# 모든 학생이 결과에 포함
result = pd.merge(
    students,
    scores,
    on="학생ID",
    how="left" # left join
)
print(result)

   학생ID   이름    점수
0   101  김민준  85.0
1   102  이서연   NaN
2   103  박지훈   NaN
3   104  최유진  90.0
4   105  정현우  75.0

In [48]:
# 점수의 결측치 개수를 확인
missing_scores_count = result["점수"].isna().sum()
print("점수의 결측치 개수:", missing_scores_count)

점수의 결측치 개수: 2

In [50]:
# 점수의 평균값으로 결측치를 대체
mean_score = result["점수"].mean()
result["점수"] = result["점수"].fillna(mean_score)
print(result)

   학생ID   이름         점수
0   101  김민준  85.000000
1   102  이서연  83.333333
2   103  박지훈  83.333333
3   104  최유진  90.000000
4   105  정현우  75.000000

In [51]:
# 최종 df 출력
print(result)

   학생ID   이름         점수
0   101  김민준  85.000000
1   102  이서연  83.333333
2   103  박지훈  83.333333
3   104  최유진  90.000000
4   105  정현우  75.000000