35) DataFrame 다루기 - cut()함수 : 숫자형 -> 구간 범주형

- pandas.cut()은 연속형 숫자 데이터를 구간으로 나누어 범주형 데이터로 변환하는 함수다.

In [3]:
import pandas as pd

scores = pd.Series([45, 55, 65, 75, 85, 95])

result = pd.cut(
    scores,
    bins=[0, 60, 80, 100],       # 구간의 경계값
    labels=["하", "중", "상"]    # 각 구간에 붙일 이름
    # 0 ───── 60 ───── 80 ───── 100
    #     하       중       상
)

display(result)

0    하
1    하
2    중
3    중
4    상
5    상
dtype: category
Categories (3, str): ['하' < '중' < '상']

In [4]:
# ​labels 생략하면
result = pd.cut(
    scores,
    bins=[0, 60, 80, 100],
    right=True # 오른쪽 구간 포함 -기본값
)

display(result)

0      (0, 60]
1      (0, 60]
2     (60, 80]
3     (60, 80]
4    (80, 100]
5    (80, 100]
dtype: category
Categories (3, interval[int64, right]): [(0, 60] < (60, 80] < (80, 100]]

In [5]:
# right=False 이면
scores = pd.Series([45, 55, 65, 75, 85, 95])
result = pd.cut(
    scores,
    bins=[0, 60, 80, 100],
    right=False
)

display(result)

0      [0, 60)
1      [0, 60)
2     [60, 80)
3     [60, 80)
4    [80, 100)
5    [80, 100)
dtype: category
Categories (3, interval[int64, left]): [[0, 60) < [60, 80) < [80, 100)]

In [6]:
# cut()함수를 이용하여 범주형 구간 파생변수 추가 예

df = pd.DataFrame({
    "이름": ["철수", "영희", "민수", "지수"],
    "점수": [55, 72, 85, 95]
})

df["등급"] = pd.cut(
    df["점수"],
    bins=[0, 60, 80, 100],
    labels=["하", "중", "상"]
)

display(df)

   이름  점수 등급
0  철수  55  하
1  영희  72  중
2  민수  85  상
3  지수  95  상

36) DataFrame 다루기 - 날짜형 데이터 다루기

1. 날짜 형식으로 변환

In [7]:
import pandas as pd

df = pd.DataFrame({
    "날짜": ["2026-01-10", "2026-02-15", "2026-03-20"]
})

display(df)
display(df.dtypes)

# 문자열 → 날짜형으로 변환
df["날짜"] = pd.to_datetime(df["날짜"])

display(df)
display(df.dtypes)

           날짜
0  2026-01-10
1  2026-02-15
2  2026-03-20

날짜    str
dtype: object

          날짜
0 2026-01-10
1 2026-02-15
2 2026-03-20

날짜    datetime64[us]
dtype: object

2. dt 접근자 

- 날짜형 데이터에서 연도, 월, 일, 요일, 시간 등의 정보를 추출할 때 사용한다.

In [8]:
import pandas as pd

df = pd.DataFrame({
    "날짜": [
        "2026-01-10 09:30:00",
        "2026-02-15 14:20:00",
        "2026-03-20 18:45:00"
    ]
})

# 문자열 → 날짜형
df["날짜"] = pd.to_datetime(df["날짜"])

# 날짜 정보 추출
df["연도"] = df["날짜"].dt.year
df["월"] = df["날짜"].dt.month
df["일"] = df["날짜"].dt.day
df["요일"] = df["날짜"].dt.dayofweek

# 시간 정보
df["시"] = df["날짜"].dt.hour
df["분"] = df["날짜"].dt.minute
df["초"] = df["날짜"].dt.second

display(df)

                   날짜    연도  월   일  요일   시   분  초
0 2026-01-10 09:30:00  2026  1  10   5   9  30  0
1 2026-02-15 14:20:00  2026  2  15   6  14  20  0
2 2026-03-20 18:45:00  2026  3  20   4  18  45  0

요일을 한글로 출력

In [9]:
weekday = {
    "Monday": "월요일",
    "Tuesday": "화요일",
    "Wednesday": "수요일",
    "Thursday": "목요일",
    "Friday": "금요일",
    "Saturday": "토요일",
    "Sunday": "일요일"
}

df["요일"] = df["날짜"].dt.day_name().map(weekday)

display(df[["날짜", "요일"]])

                   날짜   요일
0 2026-01-10 09:30:00  토요일
1 2026-02-15 14:20:00  일요일
2 2026-03-20 18:45:00  금요일

3. 날짜 데이터 연산

- 날짜끼리 빼기

In [10]:
import pandas as pd

df = pd.DataFrame({
    "시작일": ["2026-01-10", "2026-02-01", "2026-03-15"],
    "종료일": ["2026-01-15", "2026-02-10", "2026-03-20"]
})

df["시작일"] = pd.to_datetime(df["시작일"])
df["종료일"] = pd.to_datetime(df["종료일"])

# 날짜 차이
df["기간"] = df["종료일"] - df["시작일"]

display(df)

         시작일        종료일     기간
0 2026-01-10 2026-01-15 5 days
1 2026-02-01 2026-02-10 9 days
2 2026-03-15 2026-03-20 5 days

날짜 차이를 일(day) 숫자로 추출

In [11]:
df["기간_일"] = (df["종료일"] - df["시작일"]).dt.days
display(df)

         시작일        종료일     기간  기간_일
0 2026-01-10 2026-01-15 5 days     5
1 2026-02-01 2026-02-10 9 days     9
2 2026-03-15 2026-03-20 5 days     5

날짜에 일수 더하기

In [12]:
df["7일후"] = df["시작일"] + pd.Timedelta(days=7)
display(df)

         시작일        종료일     기간  기간_일        7일후
0 2026-01-10 2026-01-15 5 days     5 2026-01-17
1 2026-02-01 2026-02-10 9 days     9 2026-02-08
2 2026-03-15 2026-03-20 5 days     5 2026-03-22

날짜에 월 단위 더하기

In [13]:
df["1개월후"] = df["시작일"] + pd.DateOffset(months=1)
display(df)

         시작일        종료일     기간  기간_일        7일후       1개월후
0 2026-01-10 2026-01-15 5 days     5 2026-01-17 2026-02-10
1 2026-02-01 2026-02-10 9 days     9 2026-02-08 2026-03-01
2 2026-03-15 2026-03-20 5 days     5 2026-03-22 2026-04-15

4. 날짜 범위 생성
- pd.date_range()는 시작 날짜부터 일정한 간격으로 날짜를 자동 생성하는 함수다. 날짜 데이터 만들 때 많이 사용한다.

In [14]:
import pandas as pd

dates = pd.date_range(
    start="2026-01-01",
    end="2026-01-05"
)

display(dates)

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05'],
              dtype='datetime64[us]', freq='D')

periods로 개수 지정

In [15]:
dates = pd.date_range(
    start="2026-01-01",
    periods=5
)

display(dates)

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05'],
              dtype='datetime64[us]', freq='D')

freq로 간격 지정

In [16]:
dates = pd.date_range(
    start="2026-01-01",
    periods=5,
    freq="2D"
)

display(dates)

DatetimeIndex(['2026-01-01', '2026-01-03', '2026-01-05', '2026-01-07',
               '2026-01-09'],
              dtype='datetime64[us]', freq='2D')

데이터프레임의 날짜 컬럼 만들기

In [17]:
df = pd.DataFrame({
    "날짜": pd.date_range(
        start="2026-01-01",
        periods=5,
        freq="D"
    ),
    "매출": [100, 120, 150, 130, 180]
})

display(df)

          날짜   매출
0 2026-01-01  100
1 2026-01-02  120
2 2026-01-03  150
3 2026-01-04  130
4 2026-01-05  180

In [18]:
import pandas as pd

df = pd.DataFrame({
    "상품": ["노트북", "마우스", "키보드", "모니터", "태블릿"],
    "판매량": [10, 20, 15, 8, 12]
})

# 날짜 컬럼 추가
df["날짜"] = pd.date_range(
    start="2026-01-01",
    periods=len(df),
    freq="D"
)

display(df)

    상품  판매량         날짜
0  노트북   10 2026-01-01
1  마우스   20 2026-01-02
2  키보드   15 2026-01-03
3  모니터    8 2026-01-04
4  태블릿   12 2026-01-05

일주일 간격으로 날짜 추가

In [19]:
df["날짜2"] = pd.date_range(
    start="2026-01-01",
    periods=len(df),
    freq="W"
)

display(df)

    상품  판매량         날짜        날짜2
0  노트북   10 2026-01-01 2026-01-04
1  마우스   20 2026-01-02 2026-01-11
2  키보드   15 2026-01-03 2026-01-18
3  모니터    8 2026-01-04 2026-01-25
4  태블릿   12 2026-01-05 2026-02-01

연도, 월, 일이 각각 별도의 컬럼으로 있을 때 하나의 날짜형 파생변수 생성

In [25]:
import pandas as pd

df = pd.DataFrame({
    "연도": [2026, 2026, 2026],
    "월": [1, 2, 3],
    "일": [10, 15, 20],
    "매출": [100, 150, 200]
})

df["날짜"] = pd.to_datetime({
    "year": df["연도"],
    "month": df["월"],
    "day": df["일"]
})

display(df)

     연도  월   일   매출         날짜
0  2026  1  10  100 2026-01-10
1  2026  2  15  150 2026-02-15
2  2026  3  20  200 2026-03-20

37) DataFrame 다루기 - 문자형 데이터 다루기

1. str 접근자
- pandas의 .str 접근자는 Series의 문자열을 한꺼번에 처리할 때 사용한다.

1. .str.upper(): 대문자
2. .str.lower(): 소문자
3. .str.len(): 문자열 길이
4. .str.strip(): 앞뒤 공백 제거
5. .str.contains(): 특정 문자열 포함 여부
6. .str.startswith(): 특정 문자열로 시작
7. .str.endswith(): 특정 문자열로 끝남
8. .str.replace(): 문자열 변경
9. .str[:n]: 앞에서 n개 추출
10. .str.split(): 문자열 분리

In [26]:
import pandas as pd

df = pd.DataFrame({
    "이름": ["kim", "LEE", "park"],
    "상품명": ["노트북", "마우스", "키보드"]
})

# 대문자
df["이름_대문자"] = df["이름"].str.upper()

# 소문자
df["이름_소문자"] = df["이름"].str.lower()

display(df)

     이름  상품명 이름_대문자 이름_소문자
0   kim  노트북    KIM    kim
1   LEE  마우스    LEE    lee
2  park  키보드   PARK   park

In [27]:
df["상품명_길이"] = df["상품명"].str.len()

display(df)

     이름  상품명 이름_대문자 이름_소문자  상품명_길이
0   kim  노트북    KIM    kim       3
1   LEE  마우스    LEE    lee       3
2  park  키보드   PARK   park       3

In [28]:
df["노트북포함"] = df["상품명"].str.contains("노트북")

display(df)

     이름  상품명 이름_대문자 이름_소문자  상품명_길이  노트북포함
0   kim  노트북    KIM    kim       3   True
1   LEE  마우스    LEE    lee       3  False
2  park  키보드   PARK   park       3  False

In [29]:
result = df[df["상품명"].str.contains("노트북")]

display(result)

    이름  상품명 이름_대문자 이름_소문자  상품명_길이  노트북포함
0  kim  노트북    KIM    kim       3   True

문자열 일부 추출

In [30]:
df["이름_앞2글자"] = df["이름"].str[:2]

display(df)

     이름  상품명 이름_대문자 이름_소문자  상품명_길이  노트북포함 이름_앞2글자
0   kim  노트북    KIM    kim       3   True      ki
1   LEE  마우스    LEE    lee       3  False      LE
2  park  키보드   PARK   park       3  False      pa

앞뒤 공백제거

In [31]:
df = pd.DataFrame({
    "이름": ["  김철수", "이영희  ", "  박민수  "]
})

df["이름"] = df["이름"].str.strip()

display(df)

    이름
0  김철수
1  이영희
2  박민수

문자열 분리

In [32]:
df = pd.DataFrame({
    "이메일": [
        "kim@gmail.com",
        "lee@naver.com",
        "park@daum.net"
    ]
})

df[["아이디", "도메인"]] = df["이메일"].str.split("@", expand=True)

display(df)

             이메일   아이디        도메인
0  kim@gmail.com   kim  gmail.com
1  lee@naver.com   lee  naver.com
2  park@daum.net  park   daum.net

2. 정규표현식 사용

- contains()는 찾아서 True/False를 반환
- extract()는 찾은 내용을 반환

예제에 사용되는 정규표현식

숫자가 포함되어 있는지 / 숫자 추출

In [33]:
import pandas as pd

df = pd.DataFrame({
    "코드": ["A100", "B200", "ABC", "C300"]
})

# 숫자가 포함되어 있는지 확인
# \d → 숫자
# + → 1개 이상
df["숫자포함"] = df["코드"].str.contains(r"\d+")

# 숫자 추출
df["숫자"] = df["코드"].str.extract(r"(\d+)")

display(df)

     코드   숫자포함   숫자
0  A100   True  100
1  B200   True  200
2   ABC  False  NaN
3  C300   True  300

영문 대문자가 있는지 / 영문 추출

In [34]:
df = pd.DataFrame({
    "코드": ["A100", "B200", "123", "C300"]
})

df["영문포함"] = df["코드"].str.contains(r"[A-Z]")
df["영문"] = df["코드"].str.extract(r"([A-Z])")

display(df)

     코드   영문포함   영문
0  A100   True    A
1  B200   True    B
2   123  False  NaN
3  C300   True    C

전화번호 형식 / 전화번호 추출

In [35]:
df = pd.DataFrame({
    "전화번호": [
        "010-1234-5678",
        "02-123-4567",
        "01012345678"
    ]
})

# {3} → 정확히 3개
# {4} → 정확히 4개

df["전화번호형식"] = df["전화번호"].str.contains(
    r"\d{3}-\d{4}-\d{4}"
)

df["전화번호"] = df["전화번호"].str.extract(
    r"(\d{3}-\d{4}-\d{4})"
)

display(df)

            전화번호  전화번호형식
0  010-1234-5678    True
1            NaN   False
2            NaN   False

이메일 주소 / 이메일 도메인 추출

In [36]:
df = pd.DataFrame({
    "이메일": [
        "kim@gmail.com",
        "lee@naver.com",
        "park@daum.net"
    ]
})

# \w+ → 문자/숫자/_가 1개 이상
# \. → 실제 . 문자
# () → extract()에서 추출할 부분

df["이메일여부"] = df["이메일"].str.contains(
    r"@\w+\.\w+"
)

df["도메인"] = df["이메일"].str.extract(
    r"@(\w+\.\w+)"
)

display(df)

             이메일  이메일여부        도메인
0  kim@gmail.com   True  gmail.com
1  lee@naver.com   True  naver.com
2  park@daum.net   True   daum.net

특정 문자로 시작하는지 / 시작 문자 추출

In [37]:
df = pd.DataFrame({
    "상품코드": ["A100", "A200", "B300", "C400"]
})

df["A로시작"] = df["상품코드"].str.contains(
    r"^A"
)

df["첫문자"] = df["상품코드"].str.extract(
    r"^([A-Z])"
)

display(df)

   상품코드   A로시작 첫문자
0  A100   True   A
1  A200   True   A
2  B300  False   B
3  C400  False   C

38) DataFrame 다루기 - 연습문제

In [39]:
# 1. score의 결측치를 중앙값으로 대체한 후 score의 합계를 구하시오.
import pandas as pd

df = pd.DataFrame({
    "score": [70, 80, 90, None, 60, 75, None, 85]
})

df["score"].fillna(df["score"].median(), inplace=True)
print("결측치 대체 후 score 합계:", df["score"].sum())

결측치 대체 후 score 합계: 460.0

C:\Users\user\AppData\Local\Temp\ipykernel_24780\731415651.py:8: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["score"].fillna(df["score"].median(), inplace=True)

In [ ]:
# 2. score가 높은 순서로 정렬한 후 상위 30% 데이터를 추출하고, 그 데이터의 평균을 구하시오.
df_sorted = df.sort_values("score", ascending=False)
top_30_percent = df_sorted.head(int(len(df_sorted) * 0.3))
print("상위 30% 데이터의 평균:", top_30_percent["score"].mean())

상위 30% 데이터의 평균: 87.5

In [ ]:
# 3. age가 30 이상 45 이하인 사람들의 income 평균을 구하시오.
df = pd.DataFrame({
    "age": [20, 25, 30, 35, 40, 45, 50],
    "income": [200, 250, 300, 350, 400, 450, 500]
})

df_filtered = df[(df["age"] >= 30) & (df["age"] <= 45)]
average_income = df_filtered["income"].mean()
print("age가 30 이상 45 이하인 사람들의 income 평균:", average_income)

age가 30 이상 45 이하인 사람들의 income 평균: 375.0

In [42]:
# 4. value에서 평균 + 2×표준편차보다 큰 값을 이상치라고 할 때, 이상치의 합을 구하시오.
df = pd.DataFrame({
    "value": [10, 12, 13, 15, 16, 17, 18, 20, 100]
})

df_mean = df["value"].mean()
df_std = df["value"].std()
outliers = df[df["value"] > df_mean + 2 * df_std]
print("이상치의 합:", outliers["value"].sum())

이상치의 합: 100

In [43]:
# 5. IQR 방법을 이용하여 이상치를 제거한 후 score의 평균을 구하시오.
df = pd.DataFrame({
    "score": [60, 62, 65, 67, 68, 70, 72, 75, 78, 95, 200]
})
Q1 = df["score"].quantile(0.25)
Q3 = df["score"].quantile(0.75)
IQR = Q3 - Q1
df_cleaned = df[(df["score"] >= Q1 - 1.5 * IQR) & (df["score"] <= Q3 + 1.5 * IQR)]
print("IQR 방법을 이용하여 이상치를 제거한 후 score의 평균:", df_cleaned["score"].mean())

IQR 방법을 이용하여 이상치를 제거한 후 score의 평균: 68.55555555555556

In [45]:
# 6. 2025년 데이터만 추출하여 sales의 합계를 구하시오.
df = pd.DataFrame({
    "date": [
        "2024-01-10",
        "2024-03-20",
        "2025-01-15",
        "2025-05-10",
        "2025-07-20"
    ],
    "sales": [100, 200, 150, 300, 250]
})

df["date"] = pd.to_datetime(df["date"])
df_2025 = df[df["date"].dt.year == 2025]
print("2025년 데이터의 sales 합계:", df_2025["sales"].sum())

2025년 데이터의 sales 합계: 700

In [46]:
# 7. code에서 숫자 부분만 추출하여 새로운 number 컬럼을 만들고, number의 평균을 구하시오.
df = pd.DataFrame({
    "code": [
        "A-100",
        "B-250",
        "A-300",
        "C-150"
    ]
})
df["number"] = df["code"].str.split("-").str[1].astype(int)
print("number의 평균:", df["number"].mean())

number의 평균: 200.0

In [47]:
# 8. 부서별 score 평균을 구한 후 평균이 두 번째로 높은 부서의 평균 점수를 구하시오.
df = pd.DataFrame({
    "department": ["A", "A", "B", "B", "C", "C"],
    "score": [70, 80, 90, 95, 60, 65]
})

department_avg = df.groupby("department")["score"].mean().reset_index()
department_avg_sorted = department_avg.sort_values("score", ascending=False)
second_highest_avg = department_avg_sorted.iloc[1]["score"]
print("평균이 두 번째로 높은 부서의 평균 점수:", second_highest_avg)

평균이 두 번째로 높은 부서의 평균 점수: 75.0

In [48]:
# 9. 카테고리별 sales 합계를 구하고, 가장 큰 합계를 구하시오.
df = pd.DataFrame({
    "category": ["A", "A", "B", "B", "C", "C"],
    "sales": [100, 200, 300, 100, 150, 250]
})

df_category_sum = df.groupby("category")["sales"].sum().reset_index()
max_sales = df_category_sum["sales"].max()
print("가장 큰 카테고리별 sales 합계:", max_sales)

가장 큰 카테고리별 sales 합계: 400

In [50]:
# 10-1. date를 날짜형으로 변환하시오.
# 10-2. 연도-월별 sales 합계를 구하시오. 
# 10-3. 합계가 두 번째로 큰 연도-월의 sales 합계를 구하시오.
df = pd.DataFrame({
    "date": [
        "2024-01-10", "2024-01-20",
        "2024-02-10", "2024-02-20",
        "2024-03-10", "2024-03-20",
        "2024-04-10", "2024-04-20"
    ],
    "sales": [
        100, 150,
        200, 100,
        300, 250,
        150, 100
    ]
})

df["date"] = pd.to_datetime(df["date"])
df["year_month"] = df["date"].dt.to_period("M")
df_year_month_sum = df.groupby("year_month")["sales"].sum().reset_index()
df_year_month_sum_sorted = df_year_month_sum.sort_values("sales", ascending=False)
second_highest_sales = df_year_month_sum_sorted.iloc[1]["sales"]

print("합계가 두 번째로 큰 연도-월의 sales 합계:", second_highest_sales)
print("연도-월별 sales 합계:\n", df_year_month_sum)
print("합계가 두 번째로 큰 연도-월:\n", df_year_month_sum_sorted.iloc[1])
print("합계가 두 번째로 큰 연도-월의 sales 합계:", second_highest_sales)

합계가 두 번째로 큰 연도-월의 sales 합계: 300
연도-월별 sales 합계:
   year_month  sales
0    2024-01    250
1    2024-02    300
2    2024-03    550
3    2024-04    250
합계가 두 번째로 큰 연도-월:
 year_month    2024-02
sales             300
Name: 1, dtype: object
합계가 두 번째로 큰 연도-월의 sales 합계: 300