28) DataFrame 다루기 - 데이터셋 결합하기 concat(), merge() 함수

1. concat() 함수
- 전처리 - 데이터 결합하기
- concat() 함수 : 같은 구조의 데이터를 합치는 것
- axis=0 → 행을 아래로 붙인다
- axis=1 → 열을 옆으로 붙인다
- SQL의 JOIN과는 다르다.
- concat은 단순히 축을 기준으로 이어 붙이는 것이고, 
- 공통 키를 기준으로(SQL의 JOIN 유사) 데이터를 결합하려면 merge()나 join()을 사용한다.

In [ ]:
# import pandas as pd

# pd.concat( 
#     objs, # 연결할 데이터프레임들의 리스트
#     axis=0, # 연결 축 (0: 행 방향, 1: 열 방향)
#     join="outer", # 결합 방식 ("outer", "inner")
#     ignore_index=False, # 인덱스를 무시하고 새로 생성할지 여부
#     keys=None # 결과에 키 추가할지 여부
# )

0    80
1    90
2    75
Name: 점수, dtype: int64

pandas.Series

   점수
0  80
1  90
2  75

pandas.DataFrame

join은 “공통 부분만 붙일 것인가, 전체를 유지할 것인가”를 결정하는 옵션이다. SQL문의 JOIN같은 것이 아니다.

In [1]:
import pandas as pd

df1 = pd.DataFrame({
    "이름": ["홍길동", "김철수"],
    "점수": [80, 90]
})

df2 = pd.DataFrame({
    "이름": ["이영희", "박민수"],
    "점수": [85, 95]
})

display(df1)
display(df2)

    이름  점수
0  홍길동  80
1  김철수  90

    이름  점수
0  이영희  85
1  박민수  95

ignore_index=False : 기본값

In [2]:
# axis=0 위아래 결합(기본값) -> 행추가
df = pd.concat([df1, df2], ignore_index=False, axis=0) # ignore_index 기본값 False
display(df)

    이름  점수
0  홍길동  80
1  김철수  90
0  이영희  85
1  박민수  95

ignore_index=True

In [3]:
df = pd.concat([df1, df2], ignore_index=True, axis=0)
display(df)

    이름  점수
0  홍길동  80
1  김철수  90
2  이영희  85
3  박민수  95

axis=1 : 생략하면 기본값 0

In [4]:
# axis=0 좌우 결합 -> 열추가
df = pd.concat([df1, df2], axis=1) # axis=0 행축, axix=1 열축 기본값 0
display(df)

    이름  점수   이름  점수
0  홍길동  80  이영희  85
1  김철수  90  박민수  95

- join="outer" vs join="inner"
- join은 “공통 부분만 붙일 것인가, 전체를 유지할 것인가”를 결정

In [5]:
df1 = pd.DataFrame({
    "이름": ["김민수", "이서연"],
    "점수": [80, 90]
})

df2 = pd.DataFrame({
    "이름": ["박지훈", "최유진"],
    "등급": ["A", "B"]
})
display(df1)
display(df2)

    이름  점수
0  김민수  80
1  이서연  90

    이름 등급
0  박지훈  A
1  최유진  B

두 데이터 프레임의 공통된 열은 "이름"열만 존재한다.

In [6]:
df = pd.concat([df1, df2], join="outer", ignore_index=True) # join생략하면 기본값이 outer
display(df)

    이름    점수   등급
0  김민수  80.0  NaN
1  이서연  90.0  NaN
2  박지훈   NaN    A
3  최유진   NaN    B

In [ ]:
df = pd.concat([df1, df2], join="inner", ignore_index=True) # inner join -> 공통 컬럼만 남김
display(df)

    이름
0  김민수
1  이서연
2  박지훈
3  최유진

axis=1

In [8]:
import pandas as pd

df = pd.DataFrame({
    "이름": ["홍길동", "김철수", "이영희", "박민수"],
    "점수": [90, 80, 95, 70]
})

grade = pd.DataFrame({
    "등급": ["A", "B", "A", "C"]
})

result = pd.concat([df, grade], axis=1)

display(result)

    이름  점수 등급
0  홍길동  90  A
1  김철수  80  B
2  이영희  95  A
3  박민수  70  C

In [9]:
# 열의 개수가 다르면 -> join="outer"이면(기본값)  NaN으로 채워진다
df = pd.DataFrame({
    "이름": ["홍길동", "김철수", "이영희", "박민수"],
    "점수": [90, 80, 95, 70]
})

grade2 = pd.DataFrame({
    "등급": ["A", "B", "A"]
})

result = pd.concat([df, grade2], axis=1)

display(result)

    이름  점수   등급
0  홍길동  90    A
1  김철수  80    B
2  이영희  95    A
3  박민수  70  NaN

In [10]:
pd.concat([df, grade2], axis=1, join="inner")

    이름  점수 등급
0  홍길동  90  A
1  김철수  80  B
2  이영희  95  A

2. merge() 함수

- merge()는 두 DataFrame의 공통된 열(키)을 기준으로 데이터를 결합할 때 사용하는 함수
- SQL의 JOIN문의 경험이 있다면 merge()는 이해하기 쉽다.(JOIN 개념 자체는 동일하다)

In [11]:
import pandas as pd

df_customer = pd.DataFrame({
    "고객ID": [101, 102, 103, 104],
    "이름": ["홍길동", "김철수", "이영희", "박민수"]
})

df_score = pd.DataFrame({
    "고객ID": [101, 102, 103, 105],
    "점수": [90, 80, 95, 70]
})


display(df_customer)
display(df_score)

result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="inner" # inner(기본값), left, right, outer
)

display(result)

   고객ID   이름
0   101  홍길동
1   102  김철수
2   103  이영희
3   104  박민수

   고객ID  점수
0   101  90
1   102  80
2   103  95
3   105  70

   고객ID   이름  점수
0   101  홍길동  90
1   102  김철수  80
2   103  이영희  95

In [12]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="left"
)

display(result)

   고객ID   이름    점수
0   101  홍길동  90.0
1   102  김철수  80.0
2   103  이영희  95.0
3   104  박민수   NaN

In [13]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="right"
)

display(result)

   고객ID   이름  점수
0   101  홍길동  90
1   102  김철수  80
2   103  이영희  95
3   105  NaN  70

In [14]:
result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="outer"
)

display(result)

   고객ID   이름    점수
0   101  홍길동  90.0
1   102  김철수  80.0
2   103  이영희  95.0
3   104  박민수   NaN
4   105  NaN  70.0

- 판다스 라이브러리에는 merge() 함수와 유사한 DataFrame.merge(), DataFrame.join() 같은 메서드들도 있다. 
- 비슷한 기능을 가진 merge 메서드와 join 메서드가 존재하는 이유는 사용 상황과 코드 표현 방식이 조금 다르기 때문이다. 우선은 merge()함수으로도 충분하다.

29) DataFrame 다루기 - 결측치(누락값) 처리 1